---
title: "F1 Summary"
date: 'Last updated: `r format(Sys.Date())`'
output:
  html_document:
    dpi: 500
    fig_width: 10
    fig_height: 7
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```



```{r, echo =FALSE}

library(tidyverse)
library(formula1data) # use to download Ergast API csvs into working directory
library(magick)
library(cowplot)
library(reactable)
library(reactablefmtr)
library(gt) #for 538-themed tables
library(gtExtras)
library(glue)
library(ggtext)
library(rlang)
library(RCurl)
library(ggimage) #for working with logos
library(zoo)
library(janitor)
library(prismatic)
library(gghighlight)
library(RColorBrewer)
library(ggsci)
library(scales)
library(jsonlite)
library(httr)
library(extrafont)
library(rvest)


# Read in data from Working Directory. The downloadErgastCSV function from the formula1data package downloads a bunch of CSVs from the following link into the wd: https://ergast.com/mrd/db/

downloadErgastCSV(destfile = paste0(getwd(), "/f1db_csv"))

#read in the data using read_csv
circuits <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/circuits.csv")
constructor_results <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/constructor_results.csv")
constructor_standings <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/constructor_standings.csv")
constructors <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/constructors.csv")
driver_standings <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/driver_standings.csv")
drivers <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/drivers.csv")
lap_times <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/lap_times.csv")
pit_stops <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/pit_stops.csv")
qualifying <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/qualifying.csv")
races <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/races.csv")
results <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/results.csv")
seasons <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/seasons.csv")
status <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/status.csv")


```

 
```{r, echo = FALSE}

# create themes and other set up activities

# Custom ggplot theme (inspired by Owen Phillips at the F5 substack blog)
theme_custom <- function () { 
    theme_minimal(base_size=11, base_family="Titillium Web") %+replace% 
        theme(
            panel.grid.minor = element_blank(),
            plot.background = element_rect(fill = 'floralwhite', color = "floralwhite")
        )
}

# Define an aspect ratio to use throughout. This value is the golden ratio which provides a wider than tall rectangle
asp_ratio <- 1.618 

# Define color palette to use in tables
my_color_pal <- c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab")

# Define 538 table theme for Reactable table(s) below
theme_538 <- function() {
    reactable::reactableTheme(
        searchInputStyle = list(width = "31%", backgroundColor = "#F9F9F9"),
        style = list(
            fontFamily = "Titillium Web"
        ),
        headerStyle = list(
            "&:hover[aria-sort]" = list(
                background = "hsl(0, 0%, 80%)"),
            "&[aria-sort='ascending'], &[aria-sort='descending']" = list(
                background = "#555",
                color = "#FFF"
            ),
            borderColor = "#333"
        ),
        borderColor = "#CDCDCD"
    )
}
```
 

```{r, echo = FALSE}

##### Data Processing #####

# Create driver results dataframe
driver_results_df <- driver_standings %>% 
    left_join(races, by = "raceId") %>% 
    rename(driver_url = url) %>% 
    left_join(drivers, by = "driverId")
    

# Filter for 2021 season and fix nationalities
driver_results_2022 <- driver_results_df %>% 
    filter(year == 2022) %>% 
    mutate(Driver = paste(forename, surname)) %>%
    mutate(country = case_when(
        driverRef == "max_verstappen" ~ "Netherlands.png", 
        driverRef == "hamilton" ~ "united-kingdom.png",
        driverRef == "alonso" ~ "Spain.png",
        driverRef == "bottas" ~ "Finland.png",
        driverRef == "gasly" ~ "France.png",
        driverRef == "kevin_magnussen" ~ "Denmark.png",
        driverRef == "zhou" ~ "china.png",
        driverRef == "latifi" ~ "Canada.png",
        driverRef == "leclerc" ~ "monaco.png",
        driverRef == "norris" ~ "united-kingdom.png",
        driverRef == "ocon" ~ "France.png",
        driverRef == "perez" ~ "Mexico.png",
        driverRef == "albon" ~ "thailand.png",
        driverRef == "ricciardo" ~ "Australia.png",
        driverRef == "russell" ~ "united-kingdom.png",
        driverRef == "sainz" ~ "Spain.png",
        driverRef == "mick_schumacher" ~ "Germany.png",
        driverRef == "stroll" ~ "Canada.png",
        driverRef == "tsunoda" ~ "Japan.png",
        driverRef == "vettel" ~ "Germany.png",
        driverRef == "hulkenberg" ~ "Germany.png",
        TRUE ~ "None"
    )) %>% 
    mutate(constructor = case_when(
        driverRef == "max_verstappen" ~ "red_bull", 
        driverRef == "hamilton" ~ "mercedes",
        driverRef == "alonso" ~ "alpine",
        driverRef == "bottas" ~ "alfa",
        driverRef == "gasly" ~ "alphatauri",
        driverRef == "kevin_magnussen" ~ "haas",
        driverRef == "zhou" ~ "alfa",
        driverRef == "latifi" ~ "williams",
        driverRef == "leclerc" ~ "ferrari",
        driverRef == "albon" ~ "williams",
        driverRef == "norris" ~ "mclaren",
        driverRef == "ocon" ~ "alpine",
        driverRef == "perez" ~ "red_bull",
        driverRef == "ricciardo" ~ "mclaren",
        driverRef == "russell" ~ "mercedes",
        driverRef == "sainz" ~ "ferrari",
        driverRef == "mick_schumacher" ~ "haas",
        driverRef == "stroll" ~ "aston_martin",
        driverRef == "tsunoda" ~ "alphatauri",
        driverRef == "vettel" ~ "aston_martin",
        driverRef == "hulkenberg" ~ "aston_martin",
        TRUE ~ "None"
    )) %>% 
    mutate(manufacturer = case_when(
        driverRef == "max_verstappen" ~ "red_bull", 
        driverRef == "hamilton" ~ "mercedes",
        driverRef == "alonso" ~ "alpine",
        driverRef == "bottas" ~ "alfa",
        driverRef == "gasly" ~ "alphatauri",
        driverRef == "kevin_magnussen" ~ "haas",
        driverRef == "zhou" ~ "alfa",
        driverRef == "latifi" ~ "williams",
        driverRef == "leclerc" ~ "ferrari",
        driverRef == "albon" ~ "williams",
        driverRef == "norris" ~ "mclaren",
        driverRef == "ocon" ~ "alpine",
        driverRef == "perez" ~ "red_bull",
        driverRef == "ricciardo" ~ "mclaren",
        driverRef == "russell" ~ "mercedes",
        driverRef == "sainz" ~ "ferrari",
        driverRef == "mick_schumacher" ~ "haas",
        driverRef == "stroll" ~ "aston_martin",
        driverRef == "tsunoda" ~ "alphatauri",
        driverRef == "vettel" ~ "aston_martin",
        driverRef == "hulkenberg" ~ "aston_martin",
        TRUE ~ "None"
    )) %>% 
    mutate('driver_photo' = paste0('https://raw.githubusercontent.com/steodose/F1/master/drivers/', driverRef, '.png')) %>% 
    group_by(Driver,year) %>%
    mutate(wins = max(wins), points=max(points)) %>% 
    arrange(desc(points))


# Prepare table for Reactable
driver_table <- driver_results_2022 %>% 
    select(country, driver_photo, Driver, constructor, manufacturer, year, wins, points) %>% 
    group_by(Driver, country, year, driver_photo, constructor, manufacturer) %>% 
    summarise(wins = max(wins),
              points = max(points)) %>% 
    mutate('logo' = paste0('https://raw.githubusercontent.com/steodose/F1/master/flags/', country, '')) %>%
    mutate('constructor_logo' = paste0('https://raw.githubusercontent.com/steodose/F1/master/teams/', constructor, '.png')) %>%
    mutate('manufacturer_logo' = paste0('https://raw.githubusercontent.com/steodose/F1/master/manufacturers/', manufacturer, '.png')) %>%
    arrange(desc(points)) %>% 
    ungroup() %>% 
    mutate(rank = row_number()) %>%
    relocate(rank, logo, driver_photo, Driver, constructor_logo, manufacturer_logo) %>% 
    select(-country, -constructor, -manufacturer)


# scrape Vegas Insider futures odds

viURL <- "https://www.vegasinsider.com/auto-racing/odds/f1/"

vi_raw <- viURL %>% 
    read_html() %>% 
    html_nodes(".page-main-content li") %>%
  html_text()

# turn into a df and slice only rows 12-50 as these are the season F1 championship odds rows
vi_clean <- vi_raw %>% 
  as_tibble() %>% 
  slice(21:40) #21:40 in the beginning of the week

vi_clean <- vi_clean %>% 
  extract(value, 
    into = c("driver_constructor", "champ_odds"),
    # regex matching for any amount of consecutive non-digits at the start
    regex = "(^\\D+)(.*)", 
    convert = TRUE
  )

vi_clean$driver_constructor <- str_remove(vi_clean$driver_constructor, "[+]")
vi_clean$driver_constructor <- str_remove(vi_clean$driver_constructor, "[-]")

# create implied odds calculation...need special condition for Max Verstappen since he is favored at this point in the season
vi_clean <- vi_clean %>% 
    type_convert() %>%
  mutate(implied_odds = if_else(driver_constructor == "Max Verstappen", 1 - (100/champ_odds), 1-champ_odds/(champ_odds+100)))

# split drivers and constructors
vi_drivers <- vi_clean %>% 
  slice_head(n = 20) %>% 
  rename(driver = driver_constructor)

# Fix Sergio Perez and Alexander Albon's name in the Vegas Insider data
vi_drivers <- vi_drivers %>% 
  mutate(driver = case_when(
        driver == "Sergio Perez" ~ "Sergio Pérez",
        driver == "Alex Albon" ~ "Alexander Albon",
        driver == "Fernando Alonso" ~ "Fernando Alonzo",
        TRUE ~ driver
    ))


# do the same for next race winning odds
vi_clean_race <- vi_raw %>% 
  as_tibble() %>% 
  slice(1:20) 

vi_clean_race <- vi_clean_race %>% 
  extract(value, 
    into = c("driver", "next_race_odds"),
    # regex matching for any amount of consecutive non-digits at the start
    regex = "(^\\D+)(.*)", 
    convert = TRUE
  )

vi_clean_race$driver <- str_remove(vi_clean_race$driver, "[+]")
vi_clean_race$driver <- str_remove(vi_clean_race$driver, "[-]")

vi_clean_race <- vi_clean_race %>% 
    type_convert() %>% 
    mutate(next_race_implied_odds = 1-next_race_odds/(next_race_odds+100))

# Fix Sergio Perez and Alexander Albon's name in the Vegas Insider data
vi_clean_race <- vi_clean_race %>% 
  mutate(driver = case_when(
        driver == "Sergio Perez" ~ "Sergio Pérez",
        driver == "Alex Albon" ~ "Alexander Albon",
        TRUE ~ driver
    ))


# join into drivers table
driver_table <- left_join(driver_table, vi_drivers, by = c("Driver" = "driver"))

#join in next race odds too
driver_table <- left_join(driver_table, vi_clean_race, by = c("Driver" = "driver"))

driver_table <- driver_table %>% 
  select(-champ_odds, -next_race_odds)

# Create Reactable table

summary_table <- reactable(
  driver_table,
  theme = theme_538,
  columnGroups = list(
                      colGroup(name = "Via Vegas Insider", 
                               columns = c("implied_odds", "next_race_implied_odds"))
                      ),

                  showSortIcon = TRUE,
                  searchable = TRUE,
                  language = reactableLang(
                      searchPlaceholder = "SEARCH FOR A DRIVER"),
                  defaultPageSize = 100,
                  columns = list(
                      rank = colDef(name = "Rank",
                                       align = "center"),
                      Driver = colDef(name = "Driver",
                                      minWidth = 160,
                                       align = "left"),
                      year = colDef(name = "Year",
                                         style = list(borderRight = "2px solid #555"),
                                       align = "right"),
                      wins = colDef(name = "Wins",
                                       align = "right"),
                      points = colDef(name = "Points",
                                      align = "right",
                                      style = color_scales(driver_table, colors = my_color_pal),
                                      format =  colFormat(digits = 0)),
                      implied_odds = colDef(name = "Champ Odds",
                                      style = color_scales(driver_table, colors = paletteer::paletteer_d(
                                               palette = "ggsci::amber_material")),
                                      format =  colFormat(percent = TRUE, digits = 0),
                                       align = "right"),
                      next_race_implied_odds = colDef(name = "Next Race Odds",
                                      style = color_scales(driver_table, colors = paletteer::paletteer_d(
                                               palette = "ggsci::amber_material")),
                                      format =  colFormat(percent = TRUE, digits = 0),
                                       align = "right"),
                      
                      ### add logos using embed_img()
                      logo = colDef(
                          name = "",
                          maxWidth = 40,
                          align = "right",
                          cell = embed_img(height = "25", width = "30")
                      ),
                      driver_photo = colDef(
                          name = "",
                          maxWidth = 40,
                          align = "right",
                          cell = embed_img(height = "25", width = "30")
                      ),
                      constructor_logo = colDef(
                          name = "",
                          minWidth = 100,
                          align = "right",
                          cell = embed_img(height = "25", width = "70")
                      ),
                      manufacturer_logo = colDef(
                          name = "",
                          maxWidth = 50,
                          align = "right",
                          cell = embed_img(height = "25", width = "30")
                      )),
  
                  pagination = FALSE,
                  compact = TRUE, 
                  borderless = FALSE, 
                  striped = FALSE,
                  fullWidth = FALSE, 
                  defaultColDef = colDef(align = "center", minWidth = 95)
        ) %>% 
  add_title("2022 Formula 1 Driver Standings",
            font_size = 28) %>% 
  add_subtitle("Click a column header to sort by that statistic.",
               font_size = 14,
               font_weight = "normal") %>% 
  add_source("Data: Ergast API")

summary_table

```

