---
title: "Races"
date: 'Last updated: `r format(Sys.Date())`'
output:
  html_document:
    dpi: 500
    fig_width: 10
    fig_height: 7
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

Below you'll find figures showing the current F1 standings and key advanced metrics I'm tracking for all 20 drivers and 10 teams.

```{r, echo =FALSE}

library(tidyverse)
library(formula1data) # use to download Ergast API csvs into working directory
library(magick)
library(cowplot)
library(reactable)
library(reactablefmtr)
library(gt) #for 538-themed tables
library(gtExtras)
library(glue)
library(ggtext)
library(rlang)
library(RCurl)
library(ggimage) #for working with logos
library(zoo)
library(janitor)
library(prismatic)
library(gghighlight)
library(RColorBrewer)
library(ggsci)
library(scales)
library(jsonlite)
library(httr)
library(extrafont)
library(rvest)


# Read in data from Working Directory. The downloadErgastCSV function from the formula1data package downloads a bunch of CSVs from the following link into the wd: https://ergast.com/mrd/db/

#read in the data using read_csv
circuits <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/circuits.csv")
constructor_results <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/constructor_results.csv")
constructor_standings <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/constructor_standings.csv")
constructors <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/constructors.csv")
driver_standings <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/driver_standings.csv")
drivers <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/drivers.csv")
lap_times <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/lap_times.csv")
pit_stops <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/pit_stops.csv")
qualifying <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/qualifying.csv")
races <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/races.csv")
results <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/results.csv")
seasons <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/seasons.csv")
status <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/status.csv")


```

 
```{r, echo = FALSE}

# create themes and other set up activities

# Custom ggplot theme (inspired by Owen Phillips at the F5 substack blog)
theme_custom <- function () { 
    theme_minimal(base_size=11, base_family="Titillium Web") %+replace% 
        theme(
            panel.grid.minor = element_blank(),
            plot.background = element_rect(fill = 'floralwhite', color = "floralwhite")
        )
}

# Define an aspect ratio to use throughout. This value is the golden ratio which provides a wider than tall rectangle
asp_ratio <- 1.618 


# Define 538 table theme for Reactable table(s) below
theme_538 <- function() {
    reactable::reactableTheme(
        searchInputStyle = list(width = "31%", backgroundColor = "#F9F9F9"),
        style = list(
            fontFamily = "Titillium Web"
        ),
        headerStyle = list(
            "&:hover[aria-sort]" = list(
                background = "hsl(0, 0%, 80%)"),
            "&[aria-sort='ascending'], &[aria-sort='descending']" = list(
                background = "#555",
                color = "#FFF"
            ),
            borderColor = "#333"
        ),
        borderColor = "#CDCDCD"
    )
}
```

```{r, echo = FALSE}

##### Data Processing #####

# Create races dataframe
races2 <- races %>% 
    filter(year == 2022)

# filter for only first place finishers for the join
results2 <- results %>% 
    filter(position == 1)
    
# join in results
races2 <- left_join(races2, results2, by = "raceId")

#join in driver info
races2 <- left_join(races2, drivers, by = "driverId")

#join in constructor info
races2 <- left_join(races2, constructors, by = "constructorId")


# clean up for table
races3 <- races2 %>% 
    select(round, name.x, date, fastestLapTime, fastestLapSpeed, driverRef, forename, surname, constructorRef, name.y) %>% 
    mutate(driver = str_c(forename, surname, sep = " "))

races3 <- races3 %>%
    mutate(constructor = case_when(
        driverRef == "max_verstappen" ~ "red_bull", 
        driverRef == "hamilton" ~ "mercedes",
        driverRef == "alonso" ~ "alpine",
        driverRef == "bottas" ~ "alfa",
        driverRef == "gasly" ~ "alphatauri",
        driverRef == "kevin_magnussen" ~ "haas",
        driverRef == "zhou" ~ "alfa",
        driverRef == "latifi" ~ "williams",
        driverRef == "leclerc" ~ "ferrari",
        driverRef == "albon" ~ "williams",
        driverRef == "norris" ~ "mclaren",
        driverRef == "ocon" ~ "alpine",
        driverRef == "perez" ~ "red_bull",
        driverRef == "ricciardo" ~ "mclaren",
        driverRef == "russell" ~ "mercedes",
        driverRef == "sainz" ~ "ferrari",
        driverRef == "mick_schumacher" ~ "haas",
        driverRef == "stroll" ~ "aston_martin",
        driverRef == "tsunoda" ~ "alphatauri",
        driverRef == "vettel" ~ "aston_martin",
        driverRef == "hulkenberg" ~ "aston_martin",
        TRUE ~ ""
    )) %>% 
    mutate(country = case_when(
        name.x == "Bahrain Grand Prix" ~ "bahrain.png", 
        name.x == "Saudi Arabian Grand Prix" ~ "saudi-arabia.png",
        name.x == "Australian Grand Prix" ~ "Australia.png",
        name.x == "Emilia Romagna Grand Prix" ~ "Italy.png",
        name.x == "Miami Grand Prix" ~ "united-states.png",
        name.x == "Spanish Grand Prix" ~ "Spain.png",
        name.x == "Monaco Grand Prix" ~ "monaco.png",
        name.x == "Azerbaijan Grand Prix" ~ "azerbaijan.png",
        name.x == "Canadian Grand Prix" ~ "Canada.png",
        name.x == "British Grand Prix" ~ "united-kingdom.png",
        name.x == "Austrian Grand Prix" ~ "Austria.png",
        name.x == "French Grand Prix" ~ "France.png",
        name.x == "Hungarian Grand Prix" ~ "Hungary.png",
        name.x == "Belgian Grand Prix" ~ "Belgium.png",
        name.x == "Dutch Grand Prix" ~ "Netherlands.png",
        name.x == "Italian Grand Prix" ~ "Italy.png",
        name.x == "Singapore Grand Prix" ~ "singapore.png",
        name.x == "Japanese Grand Prix" ~ "Japan.png",
        name.x == "United States Grand Prix" ~ "united-states.png",
        name.x == "Mexico City Grand Prix" ~ "Mexico.png",
        name.x == "Brazilian Grand Prix" ~ "brazil.png",
        name.x == "Abu Dhabi Grand Prix" ~ "united-arab-emirates.png",
        TRUE ~ ""
    )) %>% 
    mutate(circuit = case_when(
        name.x == "Bahrain Grand Prix" ~ "bahrain.png", 
        name.x == "Saudi Arabian Grand Prix" ~ "saudi.png",
        name.x == "Australian Grand Prix" ~ "australia.png",
        name.x == "Emilia Romagna Grand Prix" ~ "emilia-romagna.png",
        name.x == "Miami Grand Prix" ~ "miami.png",
        name.x == "Spanish Grand Prix" ~ "spanish.png",
        name.x == "Monaco Grand Prix" ~ "monaco.png",
        name.x == "Azerbaijan Grand Prix" ~ "azerbaijan.png",
        name.x == "Canadian Grand Prix" ~ "canadian.png",
        name.x == "British Grand Prix" ~ "british.png",
        name.x == "Austrian Grand Prix" ~ "austrian.png",
        name.x == "French Grand Prix" ~ "french.png",
        name.x == "Hungarian Grand Prix" ~ "hungarian.png",
        name.x == "Belgian Grand Prix" ~ "belgian.png",
        name.x == "Dutch Grand Prix" ~ "dutch.png",
        name.x == "Italian Grand Prix" ~ "italian.png",
        name.x == "Singapore Grand Prix" ~ "singapore.png",
        name.x == "Japanese Grand Prix" ~ "japan.png",
        name.x == "United States Grand Prix" ~ "united-states.png",
        name.x == "Mexico City Grand Prix" ~ "mexico.png",
        name.x == "Brazilian Grand Prix" ~ "brazil.png",
        name.x == "Abu Dhabi Grand Prix" ~ "abu-dhabi.png",
        TRUE ~ ""
    ))



# Prepare table for Reactable
races4 <- races3 %>% 
  select(round:driverRef, circuit, driver, constructor, country) %>% 
  mutate('country_logo' = paste0('https://raw.githubusercontent.com/steodose/F1/master/flags/', country, '')) %>%
  mutate('driver_photo' = paste0('https://raw.githubusercontent.com/steodose/F1/master/drivers/', driverRef, '.png')) %>% 
    mutate('constructor_logo' = paste0('https://raw.githubusercontent.com/steodose/F1/master/teams/', constructor, '.png')) %>% 
  mutate('circuit_logo' = paste0('https://raw.githubusercontent.com/steodose/F1/master/circuits/', circuit)) %>% 
  select(-driverRef, -constructor, -country, -circuit) %>% 
  relocate(round, country_logo, name.x, date, circuit_logo, driver, driver_photo, constructor_logo, fastestLapTime, fastestLapSpeed)


# Make table
races_table <- reactable(
  races4,
  theme = theme_538,
                  showSortIcon = TRUE,
                  searchable = TRUE,
                  language = reactableLang(
                      searchPlaceholder = "SEARCH FOR A CIRCUIT"),
                  defaultPageSize = 100,
                  columns = list(
                      name.x = colDef(name = "Race",
                                      minWidth = 200,
                                       align = "left"),
                      round = colDef(name = "Round",
                                       align = "center"),
                       date = colDef(name = "Date",
                                      minWidth = 100,
                                       align = "center"),
                      fastestLapTime = colDef(name = "Fastest Lap",
                                       align = "left"),
                      fastestLapSpeed = colDef(name = "Fastest Speed (KPH)",
                                       align = "right"),
                      driver = colDef(name = "Winner",
                                      minWidth = 150,
                                       align = "right"),

                      ### add logos using embed_img()
                      country_logo = colDef(
                          name = "",
                          maxWidth = 40,
                          align = "right",
                          cell = embed_img(height = "25", width = "30")
                      ),
                      driver_photo = colDef(
                          name = "",
                          maxWidth = 40,
                          align = "right",
                          cell = embed_img(height = "25", width = "30")
                      ),
                       circuit_logo = colDef(
                          name = "Circuit",
                          maxWidth = 40,
                          align = "right",
                          cell = embed_img(height = "25", width = "30")
                      ),
                      constructor_logo = colDef(
                          name = "",
                          minWidth = 100,
                          align = "right",
                          cell = embed_img(height = "25", width = "70")
                      )),
  
                  pagination = FALSE,
                  compact = TRUE, 
                  borderless = FALSE, 
                  striped = FALSE,
                  fullWidth = FALSE, 
                  defaultColDef = colDef(align = "center", minWidth = 95)
        ) %>% 
  add_title("2022 Formula 1 Race Schedule",
            font_size = 28) %>% 
  add_subtitle("Click a column header to sort by that statistic.",
               font_size = 14,
               font_weight = "normal") %>% 
  add_source("Data: Ergast API")

races_table

    
```
