---
title: "Season Trends"
date: 'Last updated: `r format(Sys.Date())`'
output:
  html_document:
    toc: no
    toc_float: no
    dpi: 500
    fig_width: 10
    fig_height: 7
---


```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

Below you'll find figures showing the current F1 standings and key advanced metrics I'm tracking for all 20 drivers and 10 teams.

```{r, echo =FALSE}

library(tidyverse)
library(magick)
library(cowplot)
library(reactable)
library(reactablefmtr)
library(gt) #for 538-themed tables
library(gtExtras)
library(glue)
library(ggtext)
library(rlang)
library(RCurl)
library(ggimage) #for working with logos
library(zoo)
library(janitor)
library(prismatic)
library(gghighlight)
library(RColorBrewer)
library(ggsci)
library(scales)
library(jsonlite)
library(httr)
library(extrafont)


#read in the data using read_csv

circuits <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/circuits.csv")
constructor_results <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/constructor_results.csv")
constructor_standings <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/constructor_standings.csv")
constructors <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/constructors.csv")
driver_standings <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/driver_standings.csv")
drivers <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/drivers.csv")
lap_times <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/lap_times.csv")
pit_stops <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/pit_stops.csv")
qualifying <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/qualifying.csv")
races <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/races.csv")
results <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/results.csv")
seasons <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/seasons.csv")
status <- readr::read_csv("/Users/Stephan/Desktop/R Projects/F1/f1db_csv/status.csv")


```

 
```{r, echo = FALSE}

# create themes and other set up activities

# Custom ggplot theme (inspired by Owen Phillips at the F5 substack blog)
theme_custom <- function () { 
    theme_minimal(base_size=11, base_family="Titillium Web") %+replace% 
        theme(
            panel.grid.minor = element_blank(),
            plot.background = element_rect(fill = 'floralwhite', color = "floralwhite")
        )
}

# Define an aspect ratio to use throughout. This value is the golden ratio which provides a wider than tall rectangle
asp_ratio <- 1.618 


# Table theme
gt_theme_538 <- function(data,...) {
    data %>%
        opt_table_font(
            font = list(
                google_font("Titillium Web"),
                default_fonts()
            )
        ) %>%
        tab_style(
            style = cell_borders(
                sides = "bottom", color = "transparent", weight = px(2)
            ),
            locations = cells_body(
                columns = TRUE,
                # This is a relatively sneaky way of changing the bottom border
                # Regardless of data size
                rows = nrow(data$`_data`)
            )
        )  %>% 
        tab_options(
            column_labels.background.color = "white",
            table.border.top.width = px(3),
            table.border.top.color = "transparent",
            table.border.bottom.color = "transparent",
            table.border.bottom.width = px(3),
            column_labels.border.top.width = px(3),
            column_labels.border.top.color = "transparent",
            column_labels.border.bottom.width = px(3),
            column_labels.border.bottom.color = "black",
            data_row.padding = px(3),
            source_notes.font.size = 12,
            table.font.size = 16,
            heading.align = "left",
            ...
        ) 
}

```
 

```{r, echo = FALSE}

##### Data Processing #####

# Create driver results dataframe
driver_results_df <- driver_standings %>% 
    left_join(races, by = "raceId") %>% 
    rename(driver_url = url) %>% 
    left_join(drivers, by = "driverId")
    

# Filter for 2022 season and fix nationalities
driver_results_2022 <- driver_results_df %>% 
    filter(year == 2022) %>% 
    mutate(Driver = str_c(forename, surname, sep = " ")) %>%
    mutate(country = case_when(
        driverRef == "max_verstappen" ~ "Netherlands.png", 
        driverRef == "hamilton" ~ "united-kingdom.png",
        driverRef == "alonso" ~ "Spain.png",
        driverRef == "bottas" ~ "Finland.png",
        driverRef == "gasly" ~ "France.png",
        driverRef == "kevin_magnussen" ~ "Denmark.png",
        driverRef == "zhou" ~ "china.png",
        driverRef == "latifi" ~ "Canada.png",
        driverRef == "leclerc" ~ "monaco.png",
        driverRef == "norris" ~ "united-kingdom.png",
        driverRef == "ocon" ~ "France.png",
        driverRef == "perez" ~ "Mexico.png",
        driverRef == "albon" ~ "thailand.png",
        driverRef == "ricciardo" ~ "Australia.png",
        driverRef == "russell" ~ "united-kingdom.png",
        driverRef == "sainz" ~ "Spain.png",
        driverRef == "mick_schumacher" ~ "Germany.png",
        driverRef == "stroll" ~ "Canada.png",
        driverRef == "tsunoda" ~ "Japan.png",
        driverRef == "vettel" ~ "Germany.png",
        driverRef == "hulkenberg" ~ "Germany.png",
        TRUE ~ "None"
    )) %>% 
    mutate(constructor = case_when(
        driverRef == "max_verstappen" ~ "red_bull", 
        driverRef == "hamilton" ~ "mercedes",
        driverRef == "alonso" ~ "alpine",
        driverRef == "bottas" ~ "alfa",
        driverRef == "gasly" ~ "alphatauri",
        driverRef == "kevin_magnussen" ~ "haas",
        driverRef == "zhou" ~ "alfa",
        driverRef == "latifi" ~ "williams",
        driverRef == "leclerc" ~ "ferrari",
        driverRef == "albon" ~ "williams",
        driverRef == "norris" ~ "mclaren",
        driverRef == "ocon" ~ "alpine",
        driverRef == "perez" ~ "red_bull",
        driverRef == "ricciardo" ~ "mclaren",
        driverRef == "russell" ~ "mercedes",
        driverRef == "sainz" ~ "ferrari",
        driverRef == "mick_schumacher" ~ "haas",
        driverRef == "stroll" ~ "aston_martin",
        driverRef == "tsunoda" ~ "alphatauri",
        driverRef == "vettel" ~ "aston_martin",
        driverRef == "hulkenberg" ~ "aston_martin",
        TRUE ~ "None"
    )) %>% 
    mutate(manufacturer = case_when(
        driverRef == "max_verstappen" ~ "red_bull", 
        driverRef == "hamilton" ~ "mercedes",
        driverRef == "alonso" ~ "alpine",
        driverRef == "bottas" ~ "alfa",
        driverRef == "gasly" ~ "alphatauri",
        driverRef == "kevin_magnussen" ~ "haas",
        driverRef == "zhou" ~ "alfa",
        driverRef == "latifi" ~ "williams",
        driverRef == "leclerc" ~ "ferrari",
        driverRef == "albon" ~ "williams",
        driverRef == "norris" ~ "mclaren",
        driverRef == "ocon" ~ "alpine",
        driverRef == "perez" ~ "red_bull",
        driverRef == "ricciardo" ~ "mclaren",
        driverRef == "russell" ~ "mercedes",
        driverRef == "sainz" ~ "ferrari",
        driverRef == "mick_schumacher" ~ "haas",
        driverRef == "stroll" ~ "aston_martin",
        driverRef == "tsunoda" ~ "alphatauri",
        driverRef == "vettel" ~ "aston_martin",
        driverRef == "hulkenberg" ~ "aston_martin",
        TRUE ~ "None"
    )) %>% 
    mutate('driver_photo' = paste0('https://raw.githubusercontent.com/steodose/F1/master/drivers/', driverRef, '.png')) %>% 
    mutate('car_logo' = paste0('https://raw.githubusercontent.com/steodose/F1/master/teams/', constructor, '.png')) %>% 
    arrange(desc(points)) %>% 
  group_by(Driver,year) %>%
    mutate(wins = max(wins), points=max(points)) %>%
    mutate('points_name' = paste0(Driver,' (',points,')')) %>% 
    arrange(desc(points)) %>% 
  ungroup()


# get latest race date for visualizations
latest_race <- max(driver_results_2022$date)

```


### Drivers Trends

```{r, echo = FALSE}

driver_points_plot <- driver_results_2022 %>% 
  select(year, Driver, points, points_name, car_logo) %>% 
  distinct(Driver, points, points_name, car_logo) %>% 
    ggplot(aes(x = fct_reorder(points_name, points), y = points)) +
    geom_col(aes(fill = points), width = 0.6, alpha = .75) + 
    scale_fill_material("red") +
    geom_image(
        aes(
            image = car_logo                             
        ), 
        size = 0.15, 
        by = "width", 
        asp = asp_ratio
    ) +
   #coord_cartesian(clip = "off") +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20)) +
    theme_custom() + 
  #theme(plot.margin = margin(25, 25, 10, 25)) +
    theme(panel.grid.major.x = element_blank(),
          axis.text.x = element_text(face="bold"),
          axis.text.y = element_text(face="bold"),
          plot.title = element_text(face = 'bold', size = 16), 
          plot.title.position = 'plot') +
    coord_flip() +
    theme(legend.position = "none") +
    labs(x = "", 
         y = "Points", 
         title = "2022 Drivers' Championship Standings", 
         subtitle = paste0("Drivers ranked by total points earned this season. Top ten finishers receive points in the following order: 25, 18, 15, 12, 10, 8, 6, 4, 2, 1 \nwhile a bonus point is awarded for registering the fastest lap. Data as of ", format.Date(Sys.Date(), "%b. %d, %Y.")), 
         caption = "Source: Ergast API\nPlot: @steodosescu")

driver_points_plot

```


Race Results Table

```{r, echo = FALSE}

## Races Results Table
races_table <- races %>% 
    filter(year == 2022)
    
# join in results
races_table2 <- inner_join(races_table, results, by = "raceId")

#join in driver info
races_table2 <- inner_join(races_table2, drivers, by = "driverId")

#join in constructor info
races_table2 <- inner_join(races_table2, constructors, by = "constructorId")

# pivot wider and clean up df
races_table_wider <- races_table2 %>% 
  select(round, name.x, date, driverId, constructorId, positionOrder, driverRef, forename, surname, name.y) %>%
  rename(race = name.x, constructor = name.y) %>%
  mutate(driver = str_c(forename, surname, sep = " ")) %>% 
  select(-c(round, date, constructorId, driverId, driverRef:constructor)) %>% 
  pivot_wider(names_from = race,
                values_from = driver) 

# create gt table
race_results_table <- races_table_wider %>%
    gt() %>% 
    cols_label(
        positionOrder = ""
    ) %>% 
    data_color(
        columns = everything(),
        colors = scales::col_factor(
            palette = c("#FF9B00", "#FF9B00", "#FF2800", "#FF2800", "#00D2BE", "#00D2BE", "#f98e1d", "#005BA9", "#981E32", "#005BA9", "#F62039", "#f98e1d", "#00293F", "#00352F","#F62039", "#00293F", "#981E32", "#00352F", "#00A3E0", "#00A3E0", "#00352F"), 
            domain = c('Max Verstappen', 'Sergio Pérez', 'Charles Leclerc', 'Carlos Sainz', 'Lewis Hamilton', 'George Russell', 'Lando Norris', 'Esteban Ocon', 'Valtteri Bottas', 'Fernando Alonso', 'Kevin Magnussen', 'Daniel Ricciardo', 'Pierre Gasly', 'Sebastian Vettel', 'Mick Schumacher', 'Yuki Tsunoda', 'Guanyu Zhou', 'Lance Stroll', 'Alexander Albon', 'Nicholas Latifi', 'Nico Hülkenberg'),
            na.color = "white",
            ordered = TRUE
        )
    ) %>% 
    fmt_missing(
        columns = everything(),
        rows = everything(),
        missing_text = "---"
    ) %>% 
    gt_theme_538() %>%
    tab_header(title = md("**2022 Formula 1 World Championships**"),
               subtitle =glue("Race results as of {latest_race}.")) %>%
    tab_source_note(
        source_note = md("Data: Ergast API<br>Table: @steodosescu"))

race_results_table 


```

---

### Constructors Trends

```{r, echo = FALSE}

##### Constructors Analysis #####

## Constructors bar chart with race cars as bar ends

constructor_points <- constructor_results %>% 
    left_join(races, by = "raceId") %>%
    rename(race_url = url,
           race = name) %>% 
    filter(year == "2022") %>% 
    left_join(constructors, by = "constructorId")

# Make constructors standings plot
constructor_points_df <- constructor_points %>% 
    group_by(name, constructorRef) %>% 
    summarise(points = sum(points)) %>% 
    mutate(constructor = case_when(
        constructorRef == "red_bull" ~ "red_bull", 
        constructorRef == "mercedes" ~ "mercedes",
        constructorRef == "alpine" ~ "red_bull",
        constructorRef == "alfa" ~ "alfa",
        constructorRef == "mclaren" ~ "mclaren",
        constructorRef == "williams" ~ "williams",
        constructorRef == "ferrari" ~ "ferrari",
        constructorRef == "haas" ~ "haas",
        constructorRef == "aston_martin" ~ "aston_martin",
        constructorRef == "alphatauri" ~ "alphatauri",
        TRUE ~ "None"
    )) %>% 
    mutate('car_logo' = paste0('https://raw.githubusercontent.com/steodose/BlogPosts/master/Formula%201/teams/', constructorRef, '.png')) %>% 
    arrange(desc(points)) %>% 
    mutate('points_name' = paste0(name,' (',points,')'))

constructor_points_plot <- constructor_points_df %>% 
    ggplot(aes(x = fct_reorder(points_name, points), y = points)) +
    geom_col(aes(fill = points), width = 0.6, alpha = .75) + 
    scale_fill_material("blue") +
    geom_image(
        aes(
            image = car_logo                             
        ), 
        size = 0.2, 
        by = "width", 
        asp = asp_ratio
    ) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20)) +
    theme_custom() + 
    theme(panel.grid.major.x = element_blank(),
          axis.text.x = element_text(face="bold"),
          axis.text.y = element_text(face="bold"),
          plot.title = element_text(face = 'bold', size = 16), 
          plot.title.position = 'plot') + 
    coord_flip() +
    theme(legend.position = "none") +
    labs(x = "", 
         y = "Points", 
         title = "2022 Constructors' Championship Standings", 
         subtitle = paste0("Constructors ranked by total points earned this season. Top ten finishers receive points in the following order: 25, 18, 15, 12, 10, 8, 6, 4, 2, 1 \nwhile a bonus point is awarded for registering the fastest lap. Data as of ", format.Date(Sys.Date(), "%b. %d, %Y.")), 
         caption = "Source: Ergast API\nPlot: @steodosescu")

constructor_points_plot

```


```{r, echo = FALSE}

##### Make Constructors line plot #####
constructor_points2 <- constructor_points %>%
    group_by(round, race, name, constructorRef) %>% 
    summarise(points = sum(points)) %>% 
    mutate('round_race' = paste0(round,' - ',race)) %>% 
    arrange(round) %>% 
    group_by(name) %>% 
    mutate(cumulative_points = cumsum(points)) %>% 
    arrange(round) %>% 
  ungroup()

# Isolate Mercedes, Red Bull, and Ferrari for coloring of line chart
constructors_top_2 <- constructor_points2 %>% 
    filter(constructorRef == "mercedes" |
               constructorRef == "red_bull" |
             constructorRef == "ferrari")

constructors_others <- constructor_points2 %>% 
    filter(constructorRef != "mercedes" |
               constructorRef != "red_bull" | 
             constructorRef != "ferrari")

    
constructor_lineplot <- constructor_points2 %>% 
    ggplot(aes(x = round, y = cumulative_points, group = name, color = name)) +
    geom_line(aes(group = name), data = constructors_others, colour = alpha("grey", 0.7), size = 1.1) +
    geom_line(aes(colour = name), data = constructors_top_2, size = 1.1) + # colourise only the filtered data
    scale_color_manual(values=c("#FF2800", "#00D2BE", "#FF9B00")) +
    labs(x = "Race",
         y = "Cumulative F1 Points",
         title = "The Race for the Constructors' Title",
         subtitle = "Cumulative points earned for each team by race. <span style = 'color:#00D2BE;'>**Mercedes**</span>, <span style = 'color:#FF9B00;'>**Red Bull**</span> and <span style = 'color:#FF2800;'>**Ferrari**</span> are highlighted.",
         caption = "Data source: Ergast API
         Plot: @steodosescu") +
    theme_custom() +
  scale_x_continuous(breaks=seq(0, 22, 1)) +
    theme(plot.title = element_text(face = "bold"),
          plot.subtitle = element_markdown(),
          axis.text.x = element_text(face="bold"),
          axis.text.y = element_text(face="bold"),
          legend.position = "none")

constructor_lineplot

```

